# Generated by Django 5.2 on 2025-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapesphere', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
