version: '3.8'

networks:
  django-network:
    driver: bridge

volumes:
  sqlite-volume:  # SQLite verilerini saklamak için volume oluştur

services:
  mydjangoapp:
    image: mydjangoapp
    container_name: mydjangoapp
    ports:
      - "8000:8000"
    networks:
      - django-network
    volumes:
      - sqlite-volume:/app/db  # SQLite dosyalarını saklamak için volume ekle
    restart: always
